/**
 * ROV Hero Database — ข้อมูลฮีโร่ทั้งหมด 128 ตัว
 * รูปโปรไฟล์ตัวละครจริงและเป็นปัจจุบัน (ดึงจาก https://rovmeta.com/heroes)
 * ออฟไลน์ 100% รูปภาพเก็บในโฟลเดอร์ images/ โหลดไว คมชัด
 * อัปเดตล่าสุด: กันยายน 2026 (รวมฮีโร่ใหม่ ทมิฬ และ Evita)
 */
const HEROES = [
  { id:"airi", name:"Airi", role:"Assassin", role2:"Fighter", image:"images/airi.jpg", aliases:["ไอริ"] },
  { id:"aleister", name:"Aleister", role:"Mage", role2:null, image:"images/aleister.jpg", aliases:["อเลสเตอร์"] },
  { id:"alice", name:"Alice", role:"Support", role2:null, image:"images/alice.png", aliases:["อลิซ"] },
  { id:"allain", name:"Allain", role:"Fighter", role2:null, image:"images/allain.jpg", aliases:["อัลเลน"] },
  { id:"amily", name:"Amily", role:"Fighter", role2:"Assassin", image:"images/amily.png", aliases:["เอมิลี่"] },
  { id:"annette", name:"Annette", role:"Support", role2:"Mage", image:"images/annette.png", aliases:["แอนเน็ต"] },
  { id:"aoi", name:"Aoi", role:"Assassin", role2:null, image:"images/aoi.jpg", aliases:["อาโออิ"] },
  { id:"arduin", name:"Arduin", role:"Fighter", role2:"Tank", image:"images/arduin.png", aliases:["อาร์ดูอิน"] },
  { id:"arum", name:"Arum", role:"Tank", role2:null, image:"images/arum.png", aliases:["อรัม"] },
  { id:"astrid", name:"Astrid", role:"Fighter", role2:null, image:"images/astrid.png", aliases:["แอสตริด"] },
  { id:"ata", name:"Ata", role:"Tank", role2:"Fighter", image:"images/ata.jpg", aliases:["อาต้า"] },
  { id:"aya", name:"Aya", role:"Support", role2:null, image:"images/aya.jpg", aliases:["อายะ"] },
  { id:"azzenka", name:"Azzen'Ka", role:"Mage", role2:null, image:"images/azzenka.png", aliases:["อัซเซนก้า","AzzenKa"] },
  { id:"baldum", name:"Baldum", role:"Tank", role2:null, image:"images/baldum.png", aliases:["บัลดัม"] },
  { id:"bijan", name:"Bijan", role:"Fighter", role2:"Assassin", image:"images/bijan.png", aliases:["บีจัน"] },
  { id:"billow", name:"Billow", role:"Assassin", role2:null, image:"images/billow.jpg", aliases:["บิลโล่"] },
  { id:"biron", name:"Biron", role:"Fighter", role2:"Tank", image:"images/biron.png", aliases:["ไบรอน"] },
  { id:"bolt-baron", name:"Bolt Baron", role:"Fighter", role2:"Mage", image:"images/boltbaron.png", aliases:["โบลท์บารอน"] },
  { id:"bonnie", name:"Bonnie", role:"Mage", role2:"Support", image:"images/bonnie.png", aliases:["บอนนี่"] },
  { id:"bright", name:"Bright", role:"Assassin", role2:"Carry", image:"images/bright.jpg", aliases:["ไบร์ท"] },
  { id:"butterfly", name:"Butterfly", role:"Assassin", role2:null, image:"images/butterfly.jpg", aliases:["บัตเตอร์ฟลาย","ผีเสื้อ"] },
  { id:"capheny", name:"Capheny", role:"Carry", role2:null, image:"images/capheny.png", aliases:["คาเฟนี่"] },
  { id:"celica", name:"Celica", role:"Carry", role2:null, image:"images/celica.jpg", aliases:["เซลิก้า","Brunhilda","บรุนฮิลด้า"] },
  { id:"charlotte", name:"Charlotte", role:"Fighter", role2:"Assassin", image:"images/charlotte.jpg", aliases:["ชาร์ลอต"] },
  { id:"chaugnar", name:"Chaugnar", role:"Support", role2:"Tank", image:"images/chaugnar.png", aliases:["ช้างนา","ช้าง"] },
  { id:"cresht", name:"Cresht", role:"Tank", role2:"Support", image:"images/cresht.png", aliases:["เครช"] },
  { id:"darcy", name:"D'Arcy", role:"Mage", role2:null, image:"images/darcy.png", aliases:["ดาร์ซี่","DArcy"] },
  { id:"dextra", name:"Dextra", role:"Fighter", role2:"Tank", image:"images/dextra.jpg", aliases:["เด็กซ์ตร้า"] },
  { id:"diaochan", name:"Diao Chan", role:"Mage", role2:null, image:"images/diaochan.png", aliases:["เตียวเสี้ยน","Diaochan"] },
  { id:"dirak", name:"Dirak", role:"Mage", role2:null, image:"images/dirak.jpg", aliases:["ดิรัค"] },
  { id:"dolia", name:"Dolia", role:"Mage", role2:null, image:"images/dolia.jpg", aliases:["โดเลีย"] },
  { id:"dyadia", name:"Dyadia", role:"Mage", role2:"Support", image:"images/dyadia.jpg", aliases:["ไดอาเดีย"] },
  { id:"edras", name:"Edras", role:"Fighter", role2:null, image:"images/edras.png", aliases:["เอดราส"] },
  { id:"elandorr", name:"Eland'orr", role:"Carry", role2:null, image:"images/elandorr.jpg", aliases:["อีแลนดอร์","Elandorr"] },
  { id:"elsu", name:"Elsu", role:"Carry", role2:"Assassin", image:"images/elsu.png", aliases:["เอลซู"] },
  { id:"enzo", name:"Enzo", role:"Assassin", role2:null, image:"images/enzo.jpg", aliases:["เอนโซ่"] },
  { id:"erin", name:"Erin", role:"Mage", role2:null, image:"images/erin.png", aliases:["เอริน"] },
  { id:"errol", name:"Errol", role:"Fighter", role2:null, image:"images/errol.jpg", aliases:["เอร์รอล"] },
  { id:"evita", name:"Evita (เอวิต้า)", role:"Mage", role2:"Support", image:"images/evita.jpg", aliases:["เอวิต้า","Evita","10ปี","ครบรอบ 10 ปี"] },
  { id:"fennik", name:"Fennik", role:"Carry", role2:null, image:"images/fennik.png", aliases:["เฟนนิค"] },
  { id:"florentino", name:"Florentino", role:"Fighter", role2:"Assassin", image:"images/florentino.png", aliases:["ฟลอ","ฟลอเรนติโน่"] },
  { id:"gildur", name:"Gildur", role:"Mage", role2:"Tank", image:"images/gildur.png", aliases:["กิลเดอร์"] },
  { id:"goverra", name:"Goverra", role:"Mage", role2:null, image:"images/goverra.png", aliases:["โกเวร่า"] },
  { id:"grakk", name:"Grakk", role:"Tank", role2:"Support", image:"images/grakk.png", aliases:["กรัก"] },
  { id:"hayate", name:"Hayate", role:"Carry", role2:null, image:"images/hayate.png", aliases:["ฮายาเตะ"] },
  { id:"heino", name:"Heino", role:"Assassin", role2:null, image:"images/heino.jpg", aliases:["ไฮโน"] },
  { id:"helen", name:"Helen", role:"Support", role2:null, image:"images/helen.jpg", aliases:["เฮเลน","Peura","เพียวร่า"] },
  { id:"iggy", name:"Iggy", role:"Mage", role2:null, image:"images/iggy.jpg", aliases:["อิกกี้","IGGY"] },
  { id:"ignis", name:"Ignis", role:"Mage", role2:null, image:"images/ignis.png", aliases:["อิกนิส"] },
  { id:"illumia", name:"Illumia", role:"Mage", role2:null, image:"images/illumia.png", aliases:["อิลลูเมีย","Ilumia"] },
  { id:"ishar", name:"Ishar", role:"Mage", role2:null, image:"images/ishar.jpg", aliases:["อิชาร์"] },
  { id:"jinna", name:"Jinna", role:"Mage", role2:null, image:"images/jinna.png", aliases:["จินน่า","Jinnar"] },
  { id:"kahlii", name:"Kahlii", role:"Mage", role2:null, image:"images/kahlii.png", aliases:["คาลี่"] },
  { id:"kaine", name:"Kaine", role:"Assassin", role2:"Fighter", image:"images/kaine.png", aliases:["เคน","Batman","แบทแมน"] },
  { id:"keera", name:"Keera", role:"Assassin", role2:"Mage", image:"images/keera.jpg", aliases:["คีร่า"] },
  { id:"kilgroth", name:"Kil'Groth", role:"Fighter", role2:null, image:"images/kilgroth.png", aliases:["คิลกรอธ","KilGroth"] },
  { id:"kriknak", name:"Kriknak", role:"Assassin", role2:"Fighter", image:"images/kriknak.png", aliases:["กริกนัค","กริก"] },
  { id:"krixi", name:"Krixi", role:"Mage", role2:null, image:"images/krixi.png", aliases:["คริกซี่"] },
  { id:"krizzix", name:"Krizzix", role:"Support", role2:null, image:"images/krizzix.png", aliases:["คริซิกซ์"] },
  { id:"lauriel", name:"Lauriel", role:"Mage", role2:"Assassin", image:"images/lauriel.png", aliases:["ลอเรียล"] },
  { id:"laville", name:"Laville", role:"Carry", role2:null, image:"images/laville.jpg", aliases:["ลาวิลล์"] },
  { id:"liliana", name:"Liliana", role:"Mage", role2:"Assassin", image:"images/liliana.png", aliases:["ลิเลียน่า"] },
  { id:"lindis", name:"Lindis", role:"Carry", role2:null, image:"images/lindis.png", aliases:["ลินดิส"] },
  { id:"lorion", name:"Lorion", role:"Mage", role2:null, image:"images/lorion.jpg", aliases:["ลอเรียน"] },
  { id:"lubu", name:"Lu Bu", role:"Fighter", role2:null, image:"images/lubu.png", aliases:["ลู่บู้","LuBu"] },
  { id:"lumburr", name:"Lumburr", role:"Support", role2:"Tank", image:"images/lumburr.png", aliases:["ลัมเบอร์"] },
  { id:"maloch", name:"Maloch", role:"Fighter", role2:"Tank", image:"images/maloch.png", aliases:["มาล็อค"] },
  { id:"marja", name:"Marja", role:"Mage", role2:"Tank", image:"images/marja.png", aliases:["มาร์จ้า"] },
  { id:"max", name:"Max", role:"Fighter", role2:"Tank", image:"images/max.png", aliases:["แม็กซ์"] },
  { id:"mganga", name:"Mganga", role:"Mage", role2:"Support", image:"images/mganga.png", aliases:["มกังกา"] },
  { id:"mina", name:"Mina", role:"Tank", role2:null, image:"images/mina.png", aliases:["มิน่า"] },
  { id:"ming", name:"Ming", role:"Mage", role2:null, image:"images/ming.png", aliases:["หมิง"] },
  { id:"moren", name:"Moren", role:"Carry", role2:null, image:"images/moren.png", aliases:["มอเรน"] },
  { id:"mortos", name:"Mortos", role:"Fighter", role2:"Tank", image:"images/mortos.jpg", aliases:["มอร์ทอส","Arthur","อาเธอร์"] },
  { id:"murad", name:"Murad", role:"Assassin", role2:"Fighter", image:"images/murad.png", aliases:["มูราด"] },
  { id:"nakroth", name:"Nakroth", role:"Assassin", role2:"Fighter", image:"images/nakroth.jpg", aliases:["นาครอธ","นาค"] },
  { id:"natalya", name:"Natalya", role:"Mage", role2:null, image:"images/natalya.png", aliases:["นาตาเลีย"] },
  { id:"omega", name:"Omega", role:"Tank", role2:"Support", image:"images/omega.png", aliases:["โอเมก้า"] },
  { id:"omen", name:"Omen", role:"Fighter", role2:null, image:"images/omen.png", aliases:["โอเมน"] },
  { id:"ormarr", name:"Ormarr", role:"Tank", role2:"Fighter", image:"images/ormarr.png", aliases:["ออร์มาร์"] },
  { id:"paine", name:"Paine", role:"Assassin", role2:"Mage", image:"images/paine.jpg", aliases:["เพน"] },
  { id:"preyta", name:"Preyta", role:"Mage", role2:null, image:"images/preyta.png", aliases:["เพรย์ต้า"] },
  { id:"qi", name:"Qi", role:"Fighter", role2:"Tank", image:"images/qi.png", aliases:["ชี"] },
  { id:"quillen", name:"Quillen", role:"Assassin", role2:null, image:"images/quillen.png", aliases:["ควิลเลน"] },
  { id:"raz", name:"Raz", role:"Mage", role2:"Assassin", image:"images/raz.png", aliases:["ราซ"] },
  { id:"riktor", name:"Riktor", role:"Fighter", role2:"Assassin", image:"images/riktor.png", aliases:["ริคเตอร์"] },
  { id:"rouie", name:"Rouie", role:"Support", role2:null, image:"images/rouie.jpg", aliases:["รูอี้"] },
  { id:"rourke", name:"Rourke", role:"Fighter", role2:"Carry", image:"images/rourke.png", aliases:["รอร์ค"] },
  { id:"roxie", name:"Roxie", role:"Tank", role2:"Fighter", image:"images/roxie.jpg", aliases:["ร็อกซี่"] },
  { id:"ryoma", name:"Ryoma", role:"Fighter", role2:"Assassin", image:"images/ryoma.png", aliases:["เรียวม่า"] },
  { id:"sephera", name:"Sephera", role:"Mage", role2:"Support", image:"images/sephera.png", aliases:["เซฟีร่า"] },
  { id:"sinestrea", name:"Sinestrea", role:"Assassin", role2:"Fighter", image:"images/sinestrea.jpg", aliases:["ไซเนสเตรีย"] },
  { id:"skud", name:"Skud", role:"Fighter", role2:"Tank", image:"images/skud.png", aliases:["สกัด"] },
  { id:"slimz", name:"Slimz", role:"Carry", role2:null, image:"images/slimz.png", aliases:["สลิมซ์"] },
  { id:"stuart", name:"Stuart", role:"Assassin", role2:"Mage", image:"images/stuart.png", aliases:["สจ๊วต","Joker","โจ๊กเกอร์","The Joker"] },
  { id:"superman", name:"Superman", role:"Fighter", role2:"Tank", image:"images/superman.png", aliases:["ซูเปอร์แมน","Super man"] },
  { id:"taara", name:"Taara", role:"Tank", role2:"Fighter", image:"images/taara.png", aliases:["ทาร่า"] },
  { id:"tachi", name:"Tachi", role:"Fighter", role2:null, image:"images/tachi.png", aliases:["ทาชิ"] },
  { id:"tamyn", name:"Tamyn (ทมิฬ)", role:"Fighter", role2:"Assassin", image:"images/tamyn.jpg", aliases:["ทมิฬ","Tamyn","Tamin","ราหู","นาบิล","นาบิล อานาน","Nabil"] },
  { id:"teemee", name:"TeeMee", role:"Support", role2:"Tank", image:"images/teemee.png", aliases:["ทีมี"] },
  { id:"teeri", name:"Teeri", role:"Carry", role2:null, image:"images/teeri.jpg", aliases:["ทีรี่"] },
  { id:"telannas", name:"Tel'Annas", role:"Carry", role2:null, image:"images/telannas.jpg", aliases:["เทล","เทลแอนนัส","TelAnnas"] },
  { id:"thane", name:"Thane", role:"Tank", role2:"Fighter", image:"images/thane.png", aliases:["เธน"] },
  { id:"theflash", name:"The Flash", role:"Mage", role2:"Assassin", image:"images/theflash.png", aliases:["เดอะแฟลช","แฟลช","Flash"] },
  { id:"thorne", name:"Thorne", role:"Carry", role2:null, image:"images/thorne.jpg", aliases:["ธอร์น"] },
  { id:"toro", name:"Toro", role:"Tank", role2:"Support", image:"images/toro.png", aliases:["โทโร่"] },
  { id:"tulen", name:"Tulen", role:"Mage", role2:null, image:"images/tulen.png", aliases:["ทูเลน"] },
  { id:"valhein", name:"Valhein", role:"Carry", role2:null, image:"images/valhein.png", aliases:["แวน","แวนเฮล","วัลเฮน"] },
  { id:"veera", name:"Veera", role:"Mage", role2:null, image:"images/veera.jpg", aliases:["วีร่า"] },
  { id:"veres", name:"Veres", role:"Fighter", role2:"Assassin", image:"images/veres.png", aliases:["วีเรส"] },
  { id:"violet", name:"Violet", role:"Carry", role2:null, image:"images/violet.png", aliases:["ไวโอเล็ต"] },
  { id:"volkath", name:"Volkath", role:"Fighter", role2:null, image:"images/volkath.jpg", aliases:["โวลคาธ"] },
  { id:"wiro", name:"Wiro", role:"Tank", role2:"Fighter", image:"images/wiro.png", aliases:["วิโร่"] },
  { id:"wisp", name:"Wisp", role:"Carry", role2:null, image:"images/wisp.png", aliases:["วิสป์"] },
  { id:"wonderwoman", name:"Wonder Woman", role:"Fighter", role2:null, image:"images/wonderwoman.png", aliases:["วันเดอร์วูแมน","WonderWoman"] },
  { id:"wukong", name:"Wukong", role:"Assassin", role2:"Fighter", image:"images/wukong.jpg", aliases:["วูคอง","ลิง","WuKong"] },
  { id:"xeniel", name:"Xeniel", role:"Tank", role2:"Support", image:"images/xeniel.png", aliases:["เซเนียล"] },
  { id:"ybneth", name:"Y'bneth", role:"Tank", role2:"Fighter", image:"images/ybneth.png", aliases:["อิ๊บเนธ","Ybneth"] },
  { id:"yan", name:"Yan", role:"Fighter", role2:null, image:"images/yan.jpg", aliases:["แยน"] },
  { id:"yena", name:"Yena", role:"Fighter", role2:"Assassin", image:"images/yena.jpg", aliases:["เยน่า"] },
  { id:"yorn", name:"Yorn", role:"Carry", role2:null, image:"images/yorn.png", aliases:["ยอร์น"] },
  { id:"yue", name:"Yue", role:"Mage", role2:null, image:"images/yue.jpg", aliases:["ยู่เยว่"] },
  { id:"zanis", name:"Zanis", role:"Fighter", role2:null, image:"images/zanis.png", aliases:["ซานิส"] },
  { id:"zata", name:"Zata", role:"Mage", role2:"Assassin", image:"images/zata.jpg", aliases:["ซาต้า"] },
  { id:"zephys", name:"Zephys", role:"Fighter", role2:"Assassin", image:"images/zephys.jpg", aliases:["เซฟิส"] },
  { id:"zill", name:"Zill", role:"Mage", role2:"Assassin", image:"images/zill.png", aliases:["ซิล"] },
  { id:"zip", name:"Zip", role:"Support", role2:"Tank", image:"images/zip.jpg", aliases:["ซิป"] },
  { id:"zuka", name:"Zuka", role:"Fighter", role2:"Assassin", image:"images/zuka.png", aliases:["ซูก้า","หมีแพนด้า"] },
];
